### PR TITLE
Add Volume.resize

### PR DESCRIPTION
**Pull request by robertbreker**

### CODE REVIEW

**Comment by robertbreker** [comment]
Apologies about the refreshed merge request - I had forgotten os.close(fd) :)

**Comment by robertbreker** [comment]
@djs55,
Hmm. Thinking about this a bit more, this is not what the spec currently asks for.
According to http://djs55.github.io/xapi-storage/Volume%20plugin.html#a-resize we may *not* want Volume.resize to return the updated Volume.
This would mean that some other entity calls Volume.stat after Volume.resize separately - is this correct?

If so, I shall fix this PR.

**Comment by djs55** [comment]
Thanks!

I was talking to @franciozzy on a similar topic: should `SR.ls` return the detailed info, or should callers have to call `Volume.stat` on them individually? It turned out that his bug was caused by fixing `Volume.stat` and missing `SR.ls`: which suggests it would be less surprising if only `Volume.stat` returned the detailed volume info. If only `Volume.stat` performed `stat` it would be more like Unix. So I think we should keep `Volume.resize` returning nothing and the higher-level bit of `xapi` will call `Volume.stat` immediately afterwards anyway to update the db.

**Comment by djs55** [comment]
I'll write the higher-level bit of code now.

**Pull request merged**
